Try to fix `husky: not found`
Using Yarn2 compatible `husky install`,
because yarn2 is awesome and has strong opinions about lifecycle hooks.

https://typicode.github.io/husky/#/?id=yarn-2

https://github.com/devinrhode2/git-blame-ignore-style-formatting-post-commit-hook/actions/runs/3298381000/jobs/5440424129

LOGS:
# Publish

Run npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
  npm publish --ignore-scripts
  shell: /usr/bin/bash -e {0}
  env:
    NPM_TOKEN:
npm ERR! code 127
npm ERR! path /home/runner/work/git-blame-ignore-style-formatting-post-commit-hook/git-blame-ignore-style-formatting-post-commit-hook
npm ERR! command failed
npm ERR! command sh /tmp/prepare-9b9dd2ef.sh
npm ERR! /tmp/prepare-9b9dd2ef.sh: 1: husky: not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-10-21T14_55_30_759Z-debug-0.log
Error: Process completed with exit code 127.